### ISSUE TITLE
How to recover a address with the result of verify_eip191?

### ISSUE THREAD

**Issue by anylots** [spruceid/siwe-rs#45]
I used siwe-rs to verify the signature. The [signer] is the result of the verification. How can I recover the signer to the original eth address?
The following method is used, but the result is incorrect:

```
    use sha3::{Digest, Keccak256};

    let siwe_msg = Message::from_str(string_message).unwrap();
    let sig = <[u8; 65]>::from(signature);

    println!("{}", "verify_eip191 start");
    let signer: Vec<u8> = siwe_msg.verify_eip191(&sig)?;

    let public_key = &signer[1..];
    let process_sha3 = Keccak256::default().chain_update(public_key).finalize();
    let result_slice = process_sha3.as_slice();
    let address_recovery = hex::encode(&result_slice[12..]);

    //address_recovery  is not the expected address
```

My demo is here with only a few codes:   https://github.com/anylots/siweapp

**Comment by sbihel** [comment]
The public key returned by `verify_eip191` is compressed SEC1-encoded (https://docs.rs/k256/latest/k256/ecdsa/struct.VerifyingKey.html#method.to_bytes), but addresses are the hash of the uncompressed SEC1-encoded point.

But, if I may, `verify_eip191` already verifies the signer address so you shouldn't really need to rebuild it as you can get it from the `Message struct`. But in any case, you can copy the code in `verify_eip191` and use `k256` to write something along these lines:
```rust
    use k256::elliptic_curve::sec1::ToEncodedPoint;
    let public_key = &k256::ecdsa::VerifyingKey::from_sec1_bytes(&signer).unwrap();
    let public_key = public_key.to_encoded_point(false);
    let process_sha3 = Keccak256::default()
        .chain_update(&public_key.as_bytes()[1..])
        .finalize();
    let result_slice = process_sha3.as_slice();
    let address_recovery = hex::encode(&result_slice[12..]);
```
